appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: FI9jPZnOJk3/oEEcRMKDFsi/y5QIbUcpRhYlOg4iKriunX4hfcDKD5KrsDu3qLmGQK4asQSuIO7l9668ky7uvt+mqKlDtQtikdiBLApmU34spKqJZQmv/opvj6xRuCKJ63GsanVRPtqeaEd4fVAyzNhT968ERCb+bvREISzeu6EYXjSoX9v4Hwh9nv3l/FO+5UoGrpdBZdOlLMESqLz9HoG4Wirk3KwTkuep+SQ8Dtoc7pwTnmHRBqrG2CbZPEtzkLw54v9CwaZROKF/N40uGpF11lj1Jv0CUPnhKdluQglamKJaZFqNnNresTgJ73z50JCVsDHoEPkQM078VN1iBuN0NS8zOnmOHGjDqqHJl2LwozowuWxLPIcCc2ituVZi7yQl5OfB2VQDKPRVKeB3/AWDU9Alq6Bf4Ed90L9KSLo0qhYumP+3MaIpKl+gxOCIkbG8is0REf5JY1hmjCw+0SDlOaE+oWJ6KbervAP9BF8+4snVydDe7ByxcdEKp9mW2fqK0EJJakrKZ6pyYa9xmnxKFKfSNQ7RUCSV2QrRt1o7mT7dZNVi17gpQhsj6JVckxnmoOG4H0Ez5D7cbP+yXY3Co01KqkIn5m2JzhXJMSRR7UkF3FxcN4MgSn24ryTNqy2tnqhu6Jxf1GK+BGVP6sDM1LyTo2crpIpe8C8UjQc=
conda_forge_output_validation: true
